# Generated by Django 2.2.6 on 2019-11-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_auto_20191105_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
