# Generated by Django 2.2.6 on 2019-11-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_auto_20191105_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='webApp.tag'),
        ),
    ]
